### ISSUE TITLE
Distinguish idCommitment and rateCommitment in the code

### ISSUE THREAD

**Issue by s-tikhomirov** [waku-org/waku-rlnv2-contract#12]
The contract deals with two types of objects called "commitment": ID commitments and rate commitments. Using just "commitment" in variable names might be confusing. Suggestion: always use either `idCommitment` or `rateCommitment`, including in variable names such as `isValidCommitment` or `commitmentIndex`.

**Comment by alrevuelta** [comment]
Not sure I follow. afaik`ìdCommitment` and `rateCommitment` are different things.

uint256 rateCommitment = PoseidonT3.hash([idCommitment, userMessageLimit]);
idCommitment = hash of your rln secret.

**Comment by s-tikhomirov** [comment]
Sure, I understand they are different things. This is purely a naming issue. Some variables in the code are simply called `commitment` (or its derivative like `isValidCommitment`), and for a novice (myself included) it's not always obvious whether we're talking about ID commitment or rate commitment. I suggest always using distinct naming to free up code readers' brain cycles.

**Comment by s-tikhomirov** [comment]
Closing: this issue has been addressed as part of #13.
